language: csharp
# Needed for `NuGet.exe` and `GitVersion.exe`
mono: latest
# SDK version, based on the targeted `netstandard` / `netcoreapp` version in the projects
dotnet: 2.1.3
matrix:
  include:
    - os: linux
    - os: osx
      # .NET Core 2 requires OSX 10.12+
      # https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#macos
      # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
      osx_image: xcode9
branches:
  only:
  - master
  # We'll also build whenever there is a new commit on any branch starting with `features/`
  - /features\/.+/
install:
  # We're cloning the entire repository so that GitVersion can do its thing (by default Travis
  # is only getting a few commits)
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  # Make shell scripts executable
  - chmod +x build/dotnet-install.sh
  - chmod +x ./build.sh
  # `dotnet-install.sh` is available at: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
  # `Cake.dll` is targeting `.NET Core` `1.0.3`, so we need to install the latest `1.0.x` runtime
  # The runtime is required to run a `.NET Core` application, it's part of the `SDK`
  # https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
  - export DOTNET_RUNTIME_INSTALL_DIR="$PWD/.dotnetcli"
  - build/dotnet-install.sh --shared-runtime --version 1.0.8 --install-dir "$DOTNET_RUNTIME_INSTALL_DIR"
script:
  - ./build.sh --pack